# Exercise 4.6 - Merging

## List of contents
1. Libraries
2. Data Sets
3. Task

3.1.Merging Data Sets

## 1. Libraries

In [4]:
# libraries import

In [6]:
import pandas as pd
import numpy as np
import os

## 2. Data Sets

In [9]:
# creating path

In [11]:
path=r'/Users/konstant/Documents/Achievement 4. Instacart Basket Analysis'

In [13]:
df_ords_prior= pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders_products_prior.csv'), index_col = False)

In [15]:
df_ords_checked= pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_checked.csv'), index_col = 0)

In [17]:
df_ords_prior.shape

(32434489, 4)

In [19]:
df_ords_checked.shape

(3421083, 6)

# 3. Task

## 3.1 Merging Data Sets

In [27]:
# Checking the headings of both data frames.

In [29]:
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [31]:
df_ords_checked.head()

,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [33]:
# Checking the shape of both data frames.

In [35]:
df_ords_prior.shape

(32434489, 4)

In [37]:
df_ords_checked.shape

(3421083, 6)

In [39]:
#Testing the merger without overwriting the set.

In [41]:
pd.merge(df_ords_checked,df_ords_prior, on = ['order_id',], indicator = True)

,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both
2,2539329,1,1,2,8,NaN,12427,3,0,both
3,2539329,1,1,2,8,NaN,26088,4,0,both
4,2539329,1,1,2,8,NaN,26405,5,0,both
...,...,...,...,...,...,...,...,...,...,...
32434484,2977660,206209,13,1,12,7.0,14197,5,1,both
32434485,2977660,206209,13,1,12,7.0,38730,6,0,both
32434486,2977660,206209,13,1,12,7.0,31477,7,0,both
32434487,2977660,206209,13,1,12,7.0,6567,8,0,both
32434488,2977660,206209,13,1,12,7.0,22920,9,0,both

# 1. Proceeding to merge.

In [44]:
# merging with the key: 'order_id', without the indicator

In [46]:
df_merged_large = df_ords_checked.merge(df_ords_prior, on = 'order_id')

In [48]:
df_merged_large.head()

,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order,product_id,add_to_cart_order,reordered
0,2539329,1,1,2,8,NaN,196,1,0
1,2539329,1,1,2,8,NaN,14084,2,0
2,2539329,1,1,2,8,NaN,12427,3,0
3,2539329,1,1,2,8,NaN,26088,4,0
4,2539329,1,1,2,8,NaN,26405,5,0

In [50]:
df_merged_large.shape

(32434489, 9)

# 2. Exporting the merged file in pickle format.

In [53]:
df_merged_large.to_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_combined.pkl'))