## List of contents
1. Libraries Import
2. Data Sets Import
3. Data Wrangling
4. Task Answers

# 1. Libraries Import

In [5]:
#libraries import

In [7]:
import pandas as pd
import numpy as np
import os

# 2. Data Sets Import

In [10]:
# creating path, and importing data sets

In [12]:
path=r'/Users/konstant/Documents/Achievement 4. Instacart Basket Analysis'

In [14]:
path

'/Users/konstant/Documents/Achievement 4. Instacart Basket Analysis'

In [16]:
df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders.csv'), index_col = False)

In [18]:
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'products.csv'), index_col = False)

In [20]:
df_dep = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'departments.csv'), index_col = False)

In [26]:
df_ords.shape

(3421083, 7)

In [28]:
df_prods.shape

(49693, 5)

## 3. Data Wrangling

In [41]:
# dropping eval_set column from orders.csv

In [43]:
df_ords.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [45]:
# creating a new data frame from the original orders.csv with the actual column 'eval_set' removed

In [47]:
df_ords_2 = df_ords.drop(columns = ['eval_set'])

In [49]:
df_ords_2

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [51]:
# identifying a column that has missing infos to potentially drop

In [53]:
df_ords['days_since_prior_order'].value_counts(dropna = False)

days_since_prior_order
30.0    369323
7.0     320608
6.0     240013
4.0     221696
3.0     217005
5.0     214503
NaN     206209
2.0     193206
8.0     181717
1.0     145247
9.0     118188
14.0    100230
10.0     95186
13.0     83214
11.0     80970
12.0     76146
0.0      67755
15.0     66579
16.0     46941
21.0     45470
17.0     39245
20.0     38527
18.0     35881
19.0     34384
22.0     32012
28.0     26777
23.0     23885
27.0     22013
24.0     20712
25.0     19234
29.0     19191
26.0     19016
Name: count, dtype: int64

In [55]:
# Renaming the column 'order_dow' to something more descriptive

In [57]:
df_ords_3=df_ords_2.rename(columns = {'order_dow' : 'orders_day_of_week'}, inplace = True)

In [59]:
df_ords_2.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [61]:
# Changing the data type in column 'order_id'

In [63]:
df_ords['order_id'] = df_ords['order_id'].astype('str')

In [64]:
df_ords['order_id'].dtype

dtype('O')

### Transponding data frame df_dep -step 1
df_dep.T

In [68]:
# overwriting the old df_dep with a new DF and name

In [70]:
df_dep_t = df_dep.T

In [72]:
df_dep_t

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [74]:
# creating an index for the new DF

In [76]:
df_dep_t.reset_index()

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

In [78]:
# Now creating a new header

In [80]:
new_header = df_dep_t.iloc[0]

In [82]:
new_header

0    department
Name: department_id, dtype: object

In [84]:
# now taking the data from row 2 to create the new data frame (df_dep_t_new)

In [86]:
df_dep_t_new = df_dep_t[1:]

In [88]:
df_dep_t_new

                  0
1            frozen
2             other
3            bakery
4           produce
5           alcohol
6     international
7         beverages
8              pets
9   dry goods pasta
10             bulk
11    personal care
12     meat seafood
13           pantry
14        breakfast
15     canned goods
16       dairy eggs
17        household
18           babies
19           snacks
20             deli
21          missing

In [90]:
# assigning names to the columns in the new DF

In [92]:
df_dep_t_new.columns = new_header

In [94]:
df_dep_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [96]:
# creating a data dictionary from the new df_dep_t_new

In [98]:
data_dict = df_dep_t_new.to_dict('index')

In [100]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [102]:
# checking the headings in the data frame df_prods

In [104]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [106]:
# identifying what the department_id '19' means with data dictionary

In [108]:
print(data_dict.get('19'))

{'department': 'snacks'}

In [110]:
# creating a subset that only contains data from the department_id 19 (snacks)

In [112]:
df_snacks =  df_prods[df_prods['department_id']==19] # (first method)

In [114]:
df_snacks

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5
...,...,...,...,...,...
49666,49662,Bacon Cheddar Pretzel Pieces,107,19,3.6
49669,49665,Super Dark Coconut Ash & Banana Chocolate Bar,45,19,6.9
49670,49666,Ginger Snaps Snacking Cookies,61,19,5.2
49675,49671,Milk Chocolate Drops,45,19,3.0
49683,49679,Famous Chocolate Wafers,61,19,6.0

In [116]:
df_snacks_2 = df_prods.loc[df_prods['department_id'] == 19] # (second method)

In [118]:
df_snacks_2.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5

In [120]:
df_snacks_3 = df_prods.loc[df_prods['department_id'].isin([19])] #(third method)

In [122]:
df_snacks_3.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5

# 5. Task Answers

In [125]:
# Checking column headers

In [127]:
df_ords_2.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [129]:
# 2. Changing the data type in column 'user id'

In [131]:
df_ords_2['user_id'] = df_ords_2['user_id'].astype('str')

In [133]:
# checking the changed data type

In [135]:
df_ords_2['user_id'].dtype

dtype('O')

In [137]:
# 3. Change header name of column 'order_hour_of_day' to 'hour_of_purchase'

In [139]:
df_ords_2.rename(columns = {'order_hour_of_day' : 'hour_of_purchase'}, inplace = True)

In [141]:
df_ords_2.head()

,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [143]:
# 4. Frequency of the variable 'hour_of_purchase'

In [145]:
df_ords_2['hour_of_purchase'].value_counts(dropna=False)

hour_of_purchase
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

In [147]:
# 10:00 in the morning is the busier hour fro placing orders with a count of 288418

In [149]:
#5. Checking headers for data frame df_prods to determine the value: 4 means

In [151]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [153]:
print(data_dict.get('4'))

{'department': 'produce'}

In [155]:
# The value 4 refers to "produce"

In [157]:
#6. Subset for breakfast item sales

In [159]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [161]:
# The department_id for breakfast is 14

In [163]:
breakfast_items=df_prods[df_prods['department_id']==14]

In [165]:
breakfast_items

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6
...,...,...,...,...,...
49330,49326,Cereal Variety Fun Pack,121,14,9.1
49395,49391,Light and Fluffy Buttermilk Pancake Mix,130,14,2.0
49547,49543,Chocolate Cheerios Cereal,121,14,10.8
49637,49633,Shake 'N Pour Buttermilk Pancake Mix,130,14,14.2
49667,49663,Ultra Protein Power Crunch Peanut Butter N' Ho...,57,14,10.2

In [167]:
# 7. Subet for dinner party items (alcohol, deli, beverages, and meat/seafood)

In [169]:
dinner_party_items= df_prods.loc[df_prods['department_id'].isin([5,20,7,12])]

In [171]:
dinner_party_items

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
...,...,...,...,...,...
49676,49672,Cafe Mocha K-Cup Packs,26,7,6.5
49679,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7,14.0
49680,49676,Ultra Red Energy Drink,64,7,14.5
49686,49682,California Limeade,98,7,4.3
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3

In [173]:
# 8. The dinner_party_items data frame contains 7650 rows.

In [175]:
# 9. user_id_1 check

In [177]:
user_id_1_check=df_ords_2[df_ords['user_id']==1]

In [179]:
user_id_1_check

,order_id,user_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
5,3367565,1,6,2,7,19.0
6,550135,1,7,1,9,20.0
7,3108588,1,8,1,14,14.0
8,2295261,1,9,1,16,0.0
9,2550362,1,10,4,8,30.0
10,1187899,1,11,4,8,14.0

In [181]:
# 10. Basic stats about user_id_1

In [183]:
user_id_1_check.describe()

,order_id,order_number,orders_day_of_week,hour_of_purchase,days_since_prior_order
count,1.100000e+01,11.000000,11.000000,11.000000,10.000000
mean,1.923450e+06,6.000000,2.636364,10.090909,19.000000
std,1.071950e+06,3.316625,1.286291,3.477198,9.030811
min,4.315340e+05,1.000000,1.000000,7.000000,0.000000
25%,8.690170e+05,3.500000,1.500000,7.500000,14.250000
50%,2.295261e+06,6.000000,3.000000,8.000000,19.500000
75%,2.544846e+06,8.500000,4.000000,13.000000,26.250000
max,3.367565e+06,11.000000,4.000000,16.000000,30.000000

In [185]:
df_ords_2.to_csv(os.path.join(path, '02 Data','Prepared Data', 'orders_wrangled.csv'))

In [186]:
df_dep_t_new.to_csv(os.path.join(path, '02 Data','Prepared Data', 'department_wrangled.csv'))